apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: KazikKluz/aws-rds-pulumi 
    backstage.io/techdocs-ref: dir:.
    pulumi.com/project-slug: KazikKluz/aws-rds/dev
  title: 'Customized AWS RDS' 
  description: 'Provisions a customised RDS database on AWS' 
spec:
  type: service
  owner: user:KazikKluz
  lifecycle: experimental
